runtime: nodejs16  # or newer version
env: standard

instance_class: F1  # Free tier instance

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto